name: Build and Execute UI tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run Selenium Web Driver UI Tests Project 1
      run: dotnet test TestProject1 --no-build --verbosity normal
    - name: Run Selenium Web Driver UI Tests Project 2
      run: dotnet test TestProject2 --no-build --verbosity normal
    - name: Run Selenium Web Driver UI Tests Project 3
      run: dotnet test TestProject3 --no-build --verbosity normal
